<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SalesforceOpportunity extends Model
{
    protected $fillable = [
        'salesforce_id',
        'name',
        'created_date',
        'close_date',
        'amount',
        'opo_for_importe_total',
        'stage_name',
        'record_type_name',
        'owner_id',
        'owner_name',
        'owner_is_active',
        'owner_delegation',
        'delivery_store',
        'account_id',
        'account_name',
        'account_phone',
        'account_person_email',
        'account_company_email',
        'shared_delivery_id',
        'shared_delivery_name',
        'garantia_total',
        'beneficio_financiacion_comercial',
        'importe_financiado',
        'financial_commission',
        'financial_discount',
        'interest_rate',
        'financial_zone',
        'opportunity_record_type_formula',
        'financing_paid',
        'financing_paid_date',
        'financed_amount_ratio',
        'gestion_de_venta',
        'opo_div_descuento',
        'informe_rentabilidad',
        'rentabilidad_financiera',
        'vehicle_interest_id',
        'vehicle_sale_price',
        'vehicle_purchase_price',
        'vehicle_purchase_source',
        'vehicle_purchase_date',
        'vehicle_buyer_id',
        'vehicle_buyer_name',
        'vehicle_plate',
        'vehicle_entry_date',
        'vehicle_days_in_stock',
        'portal_original',
        'opportunity_source_raw',
        'opportunity_source_normalized',
        'portal_resolved',
        'portal_resolution_source',
        'portal_resolution_lead_id',
        'portal_resolution_debug',
        'reservation',
        'reservation_date',
        'cv_signed',
        'cv_signed_date',
        'raw_payload',
    ];

    protected $casts = [
        'created_date' => 'datetime',
        'close_date' => 'date',
        'amount' => 'decimal:2',
        'opo_for_importe_total' => 'decimal:2',
        'owner_is_active' => 'boolean',
        'garantia_total' => 'decimal:2',
        'beneficio_financiacion_comercial' => 'decimal:2',
        'importe_financiado' => 'decimal:2',
        'financial_commission' => 'decimal:2',
        'financial_discount' => 'decimal:2',
        'financing_paid' => 'boolean',
        'financing_paid_date' => 'date',
        'financed_amount_ratio' => 'decimal:6',
        'gestion_de_venta' => 'boolean',
        'opo_div_descuento' => 'decimal:2',
        'informe_rentabilidad' => 'decimal:2',
        'rentabilidad_financiera' => 'decimal:6',
        'vehicle_sale_price' => 'decimal:2',
        'vehicle_purchase_price' => 'decimal:2',
        'vehicle_purchase_date' => 'date',
        'vehicle_entry_date' => 'date',
        'vehicle_days_in_stock' => 'integer',
        'reservation' => 'boolean',
        'reservation_date' => 'date',
        'cv_signed' => 'boolean',
        'cv_signed_date' => 'date',
        'portal_resolution_debug' => 'array',
        'raw_payload' => 'array',
    ];
}
